# Étape 1 : build
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production
COPY . .

# Étape 2 : image finale
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000
CMD ["node", "index.js"]
